# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:    
  name: mysql1
  namespace: default        # Change your namespace
spec:
  tags: ["mysql","system","K8s"]
  message: "Warning! MySQLdump is blocked - K1 test test"
  selector:      
    matchLabels:        
      app: mysql-k1    #change with your own label    
  process:      
    matchPaths:      
    - path: /usr/bin/mysqldump    
    action: Block    
    severity: 6
